### ISSUE TITLE
Automate tasks with Gulp

### ISSUE THREAD

**Issue by mawuli** [kaopoku/ahonyabid-scraper#3]
Use Gulp to automate the following tasks:

- run unit tests
- run/serve web app
- generate docs
- run code linter to do style and type checks

For documentation generation, you can use something like [JsDoc](usejsdoc.org).

And for the code linter, check out [JsLint](https://github.com/reid/node-jslint), [JsHint](http://jshint.com/)

**Comment by kaopoku** [comment]
Could use some help with the "generate docs" part. Not sure I used gulp-jsdoc well. Check it out and let me know what you think.
